# testing/experimenting
language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"
script:
  - pytest export_tests.py  # test export script
  # Phantomjs? Selenium? Neither and use python? - phantomjs testrunner.js
